### ISSUE TITLE
Error: getaddrinfo EADDRINFO

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/npmd-install#6]
idk why but on some projects, `npmd install` fails with

```
GET https://xxx
GET https://xxx

Error: getaddrinfo EADDRINFO
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

The url is not the problem, dns resolution seems to be. Could this be running out of sockets? A node bug? An os bug?

I want to try to add a concurrency limit to pull-paramap to see if too high concurrency causes this.

**Comment by dominictarr** [comment]
this is weird.
could you curl the urls that it errors on?
what is the domain that it fails on?

**Comment by juliangruber** [comment]
It's a registry https url, and works when you manually request it via `request()`, it only fails inside the npmd-install process.

Do you see a quick way to limit concurrency so we can check that? In a test I did it was installing 120 modules at once.

**Comment by dominictarr** [comment]
what is the url? can I reproduce it?
well, you could change that line to be asyncMap instead of paramap that will do them one at a time.
adding a width to paramap would also be cool, but it's a bit more work.

**Comment by juliangruber** [comment]
that's private modules again. can you point me to the async map module?

**Comment by dominictarr** [comment]
it's in the pull library: `pull.asyncMap(map)`

**Comment by juliangruber** [comment]
The error does **not** happen with `pull.asyncMap`

**Comment by juliangruber** [comment]
i'll try to get a reproducable test case without npmd

**Comment by dominictarr** [comment]
hmm, okay so if you are right about that it's too many requests, then paramap needs a width option,
I have a parallel map here: https://github.com/dominictarr/pull-stream/blob/master/throughs.js#L38
but in this case, we need a map that returns in the same order, which the module paramap does but not pull.paramap.

**Comment by dominictarr** [comment]
okay, pull-paramap@1.1.0 now supports a width (integer) parameter. `paramap(async, width)` 
can you try that?

**Comment by juliangruber** [comment]
haha wtf i can't reproduce right now, i'll try later

**Comment by juliangruber** [comment]
i have it clear the cache and install the deps in an infinite loop and it keeps succeeding, i have no idea what was going on, but on @calvinfo's machine it failed on the first run

**Comment by dominictarr** [comment]
Hmm... this is a difficult situation then...
Maybe the solution is comprehensive logging, that way would be able to have some idea of what was happening,
even if it couldn't be reproduced on my machine.

**Comment by calvinfo** [comment]
Yeah, +1 to logging - core logging doesn't really have anything useful either

```
segment site-private (master) · NODE_DEBUG=net npmd install
NET: 8446 _read
NET: 8446 Socket._read readStart
GET https://segmentio.registry.nodejitsu.com/minimatch/-/minimatch-0.2.14.tgz
NET: 8446 connect: find host segmentio.registry.nodejitsu.com
NET: 8446 _read
NET: 8446 _read wait for connection
GET https://segmentio.registry.nodejitsu.com/coffee-script/-/coffee-script-1.4.0.tgz
NET: 8446 connect: find host segmentio.registry.nodejitsu.com
NET: 8446 _read
NET: 8446 _read wait for connection
GET https://segmentio.registry.nodejitsu.com/commander/-/commander-0.6.1.tgz
NET: 8446 connect: find host segmentio.registry.nodejitsu.com
NET: 8446 _read
NET: 8446 _read wait for connection
GET https://segmentio.registry.nodejitsu.com/glob/-/glob-3.1.21.tgz
NET: 8446 connect: find host segmentio.registry.nodejitsu.com
NET: 8446 _read
NET: 8446 _read wait for connection
GET https://segmentio.registry.nodejitsu.com/jade/-/jade-0.27.7.tgz
NET: 8446 connect: find host segmentio.registry.nodejitsu.com
NET: 8446 _read
NET: 8446 _read wait for connection

....

Error: getaddrinfo EADDRINFO
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by juliangruber** [comment]
the dns node core module doesn't support node_debug, maybe i can add that to core

**Comment by juliangruber** [comment]
@calvinfo can you try with node 0.11.13? That should show the hostname (https://github.com/joyent/node/commit/a2d1cbef6baabd767cef523078eb4e5921429d09)

**Comment by juliangruber** [comment]
hmm actually nope it won't, it just adds `err.hostname`

**Comment by juliangruber** [comment]
i found the corresponding node bug: https://github.com/joyent/node/issues/7742

**Comment by juliangruber** [comment]
that's actually an EMFILE error

**Comment by juliangruber** [comment]
the error appears on **every** `request()`, so something else must be causing the high fd usage.

Setting `ulimit -n 4000` fixes it for me.

**Comment by juliangruber** [comment]
official npm also fails due to emfile, although it doesn't say so

**Comment by dominictarr** [comment]
okay so this isn't an npmd bug then?

**Comment by juliangruber** [comment]
depends on whether we want to prevent this error from showing up by using something like graceful-fs for requests

**Comment by dominictarr** [comment]
how does npm handle this?
did the new paramap work?

**Comment by juliangruber** [comment]
yup, it's gotten slower but works

**Comment by juliangruber** [comment]
nope it doesn't, just had this:

``` bash
npmd install
GET https://segmentio.registry.nodejitsu.com/redis/-/redis-0.10.3.tgz
GET https://segmentio.registry.nodejitsu.com/should/-/should-4.0.4.tgz
GET https://segmentio.registry.nodejitsu.com/s-filter-integration/-/s-filter-integration-1.1.0.tgz

Error: getaddrinfo EADDRINFO
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by dominictarr** [comment]
hmm... it's hard to figure out what the correct approach to this problem is...
maybe it's to retry on certain types of errors?

**Comment by juliangruber** [comment]
yeah the situation is hard...maybe tcp like slow start / self adaption? this could be a sweet module too

**Comment by dominictarr** [comment]
really, this is a question about how to debug production software before you have figured out how to reproduce it. maybe one approach is logging?

**Comment by juliangruber** [comment]
yeah, something like the very verbose npm-debug.log would be great, or maybe in json format so we can more easily parse and transform
